### ISSUE TITLE
Don't encode spaces

### ISSUE THREAD

**Issue by almirramic** [btrazzini/htmlentities#1]
Please make it so regular spaces do not encode with &amp;nbsp;

Regular spaces are perfectly fine in HTML. In fact &amp;nbsp; is a special non-breaking space used to make sure phrases don't break. So, encoding regular spaces with &amp;nbsp; is actually inaccurate. Coda has this functionality too and it does not encode regular spaces.

Thank you! And thank you for this extension in Nova!

**Comment by tomliv** [comment]
I should be able to select a whole paragraph and encode special characters, NOT parenthesis, square brackets, spaces etc. Or at least have some options/prefs to set for that.

**Comment by btrazzini** [comment]
@almirramic done!
